version: '3.8'

services:
  api:
    build: .
    ports:
      - "5005:5005"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
